version: '1'
services:
  db:
    image: 'postgres:16.2-alpine'
    container_name: bimbelms-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    container_name: bimbelms-app
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update